// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7OrVWV_S6MPfr_YRVuhG0HNfmrBQ8dwk',
    appId: '1:343548232760:web:372977e0e661e1406a52cd',
    messagingSenderId: '343548232760',
    projectId: 'today-i-learned-da8a3',
    authDomain: 'today-i-learned-da8a3.firebaseapp.com',
    storageBucket: 'today-i-learned-da8a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi4kbAhwpgetSPYumEPlOli9Vq8GAYjZw',
    appId: '1:343548232760:android:11ea276d8cfae1296a52cd',
    messagingSenderId: '343548232760',
    projectId: 'today-i-learned-da8a3',
    storageBucket: 'today-i-learned-da8a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQFppkr6hA2xQC6JbkUSSyy3Nbj_H6_Jw',
    appId: '1:343548232760:ios:808124ea4f264d686a52cd',
    messagingSenderId: '343548232760',
    projectId: 'today-i-learned-da8a3',
    storageBucket: 'today-i-learned-da8a3.appspot.com',
    iosBundleId: 'com.example.til',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQFppkr6hA2xQC6JbkUSSyy3Nbj_H6_Jw',
    appId: '1:343548232760:ios:7353e9dd02a3e6546a52cd',
    messagingSenderId: '343548232760',
    projectId: 'today-i-learned-da8a3',
    storageBucket: 'today-i-learned-da8a3.appspot.com',
    iosBundleId: 'com.example.til.RunnerTests',
  );
}
